### ISSUE TITLE
was used to transform files, but didn't generate a sourcemap 

### ISSUE THREAD

**Issue by garyb01** [JiangWeixian/vite-plugin-barrel#8]
**Describe the bug**
Lots of `(vite-plugin-barrel:transform plugin) Sourcemap is likely to be incorrect: a plugin (vite-plugin-barrel:transform) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help` when building with sourcemaps enabled

**Expected behavior**
No warnings/errors in console

**Comment by JiangWeixian** [comment]
Try `vite-plugin-barrel@0.0.0-snapshot-20240121111118`, if not working please provide mini reproduction repo
